package cli

import (
	"fmt"
	"io"
	"sort"
	"strings"
	"text/tabwriter"

	"github.com/tobiash/gitops-preview-toolkit/pkg/ai"
	"github.com/tobiash/gitops-preview-toolkit/pkg/diff"
	"github.com/tobiash/gitops-preview-toolkit/pkg/policy"
)

func writeDiffSummary(out io.Writer, result *diff.DiffResult, policyResult *policy.Result) error {
	if result == nil {
		return nil
	}

	if _, err := fmt.Fprintln(out, classifyDiff(result)); err != nil {
		return err
	}

	summary := result.Summary()
	if summary.Total == 0 {
		_, err := fmt.Fprintln(out, "✅ No resource changes.")
		return err
	}

	if _, err := fmt.Fprintf(
		out,
		"🟢 %d to add, 🟡 %d to change, 🔴 %d to destroy.\n\n",
		len(result.Added),
		len(result.Modified),
		len(result.Deleted),
	); err != nil {
		return err
	}

	rows := sortedKindBreakdownRows(summary.KindBreakdown)
	if len(rows) == 0 {
		return nil
	}

	if _, err := fmt.Fprintln(out, "Changed resources by kind:"); err != nil {
		return err
	}

	tw := tabwriter.NewWriter(out, 0, 0, 2, ' ', 0)
	if _, err := fmt.Fprintln(tw, "KIND\tADDED\tMODIFIED\tDELETED\tTOTAL"); err != nil {
		return err
	}
	for _, row := range rows {
		if _, err := fmt.Fprintf(
			tw,
			"%s\t%d\t%d\t%d\t%d\n",
			row.Kind,
			row.Added,
			row.Modified,
			row.Deleted,
			row.Total,
		); err != nil {
			return err
		}
	}
	if err := tw.Flush(); err != nil {
		return err
	}

	if _, err := fmt.Fprintln(out); err != nil {
		return err
	}
	return writePolicySummary(out, policyResult)
}

func classifyDiff(result *diff.DiffResult) string {
	total := result.TotalChanged()
	if total == 0 {
		return "No manifest changes detected."
	}

	added := len(result.Added)
	modified := len(result.Modified)
	deleted := len(result.Deleted)

	switch dominantChangeKind(added, modified, deleted, total) {
	case "added":
		return "Mostly additive changes detected."
	case "modified":
		return "Mostly in-place changes detected."
	case "deleted":
		return "Mostly destructive changes detected."
	default:
		return "Mixed manifest changes detected."
	}
}

func dominantChangeKind(added, modified, deleted, total int) string {
	threshold := total * 7
	if added*10 >= threshold {
		return "added"
	}
	if modified*10 >= threshold {
		return "modified"
	}
	if deleted*10 >= threshold {
		return "deleted"
	}
	return ""
}

type kindBreakdownRow struct {
	Kind     string
	Added    int
	Modified int
	Deleted  int
	Total    int
}

func sortedKindBreakdownRows(m map[string]diff.ChangeBreakdown) []kindBreakdownRow {
	if len(m) == 0 {
		return nil
	}

	rows := make([]kindBreakdownRow, 0, len(m))
	for kind, row := range m {
		rows = append(rows, kindBreakdownRow{
			Kind:     kind,
			Added:    row.Added,
			Modified: row.Modified,
			Deleted:  row.Deleted,
			Total:    row.Total,
		})
	}

	sort.Slice(rows, func(i, j int) bool {
		if rows[i].Total == rows[j].Total {
			return rows[i].Kind < rows[j].Kind
		}
		return rows[i].Total > rows[j].Total
	})

	return rows
}

func writePolicySummary(out io.Writer, result *policy.Result) error {
	if result == nil {
		return nil
	}

	if len(result.Classifications) > 0 {
		if _, err := fmt.Fprintln(out, "Classifications:"); err != nil {
			return err
		}
		for _, item := range summarizePolicyClassifications(result.Classifications) {
			if _, err := fmt.Fprintf(out, "- %s [%s] (%d)\n", item.id, item.provenance, item.count); err != nil {
				return err
			}
		}
		if _, err := fmt.Fprintln(out); err != nil {
			return err
		}
	}

	if len(result.Violations) > 0 {
		if _, err := fmt.Fprintln(out, "Violations:"); err != nil {
			return err
		}
		for _, violation := range result.Violations {
			message := violation.Message
			if message == "" {
				message = violation.ID
			}
			if _, err := fmt.Fprintf(out, "- %s: %s\n", violation.ID, message); err != nil {
				return err
			}
		}
		if _, err := fmt.Fprintln(out); err != nil {
			return err
		}
	}

	if len(result.Labels) > 0 {
		if _, err := fmt.Fprintln(out, "Suggested labels:"); err != nil {
			return err
		}
		for _, label := range result.Labels {
			if _, err := fmt.Fprintf(out, "- %s\n", label); err != nil {
				return err
			}
		}
		if _, err := fmt.Fprintln(out); err != nil {
			return err
		}
	}

	if result.PolicyFailed {
		if _, err := fmt.Fprintln(out, "Policy enforcement failed:"); err != nil {
			return err
		}
		for _, id := range result.PolicyFailures {
			if _, err := fmt.Fprintf(out, "- %s\n", id); err != nil {
				return err
			}
		}
		if _, err := fmt.Fprintln(out); err != nil {
			return err
		}
	}

	return nil
}

func writeAISummary(out io.Writer, assessment *ai.Assessment) error {
	if assessment == nil {
		return nil
	}
	if _, err := fmt.Fprintln(out, "AI Assessment:"); err != nil {
		return err
	}
	if _, err := fmt.Fprintf(out, "Generated by %s", assessment.Provider); err != nil {
		return err
	}
	if assessment.Model != "" {
		if _, err := fmt.Fprintf(out, " using %s", assessment.Model); err != nil {
			return err
		}
	}
	if _, err := fmt.Fprintln(out, ". Review generated content before acting on it."); err != nil {
		return err
	}
	if assessment.Summary != "" {
		if _, err := fmt.Fprintf(out, "%s\n", assessment.Summary); err != nil {
			return err
		}
	}
	if assessment.Truncated {
		if _, err := fmt.Fprintln(out, "AI input was truncated; assessment may not cover every diff detail."); err != nil {
			return err
		}
	}
	return nil
}

type summarizedPolicyClassification struct {
	id         string
	provenance string
	count      int
}

func summarizePolicyClassifications(items []policy.Classification) []summarizedPolicyClassification {
	counts := make(map[string]int)
	for _, item := range items {
		provenance := item.Provenance
		if provenance == "" {
			provenance = "policy"
		}
		counts[item.ID+"\x00"+provenance]++
	}
	rows := make([]summarizedPolicyClassification, 0, len(counts))
	for key, count := range counts {
		parts := strings.SplitN(key, "\x00", 2)
		rows = append(rows, summarizedPolicyClassification{id: parts[0], provenance: parts[1], count: count})
	}
	sort.Slice(rows, func(i, j int) bool {
		if rows[i].count == rows[j].count {
			if rows[i].id == rows[j].id {
				return rows[i].provenance < rows[j].provenance
			}
			return rows[i].id < rows[j].id
		}
		return rows[i].count > rows[j].count
	})
	return rows
}
