package config

import (
	"os"
	"path/filepath"
	"testing"
)

func TestDiscoverConfigPath_FindsFMPYAML(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, dir, ".fmp.yaml", "sort: true\n")

	got := DiscoverConfigPath(dir)
	want := filepath.Join(dir, ".fmp.yaml")
	if got != want {
		t.Errorf("DiscoverConfigPath() = %q, want %q", got, want)
	}
}

func TestDiscoverConfigPath_PrefersToolkitConfig(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, dir, ".fmp.yaml", "paths: [legacy]\n")
	writeFile(t, dir, ".gitops-preview.yaml", "paths: [current]\ncrossplane:\n  enabled: true\n  timeout: 2m\n")
	cfg, err := LoadConfig(dir)
	if err != nil {
		t.Fatal(err)
	}
	if len(cfg.Paths) != 1 || cfg.Paths[0] != "current" || filepath.Base(cfg.SourcePath) != ".gitops-preview.yaml" {
		t.Fatalf("unexpected discovered config: %#v", cfg)
	}
	if cfg.Crossplane == nil || !BoolOr(cfg.Crossplane.Enabled, false) || cfg.Crossplane.Timeout != "2m" {
		t.Fatalf("Crossplane preferences missing: %#v", cfg.Crossplane)
	}
}

func TestDiscoverConfigPath_FindsFMPYML(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, dir, ".fmp.yml", "sort: true\n")

	got := DiscoverConfigPath(dir)
	want := filepath.Join(dir, ".fmp.yml")
	if got != want {
		t.Errorf("DiscoverConfigPath() = %q, want %q", got, want)
	}
}

func TestDiscoverConfigPath_FindsGitHubFMPYAML(t *testing.T) {
	dir := t.TempDir()
	mkdir(t, dir, ".github")
	writeFile(t, dir, ".github/fmp.yaml", "sort: true\n")

	got := DiscoverConfigPath(dir)
	want := filepath.Join(dir, ".github/fmp.yaml")
	if got != want {
		t.Errorf("DiscoverConfigPath() = %q, want %q", got, want)
	}
}

func TestDiscoverConfigPath_PrefersRootConfig(t *testing.T) {
	dir := t.TempDir()
	mkdir(t, dir, ".github")
	writeFile(t, dir, ".fmp.yaml", "sort: true\n")
	writeFile(t, dir, ".github/fmp.yaml", "sort: false\n")

	got := DiscoverConfigPath(dir)
	if filepath.Base(got) != ".fmp.yaml" {
		t.Errorf("expected root .fmp.yaml to be preferred, got %q", got)
	}
}

func TestDiscoverConfigPath_PrefersYAMLOverYML(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, dir, ".fmp.yaml", "sort: true\n")
	writeFile(t, dir, ".fmp.yml", "sort: false\n")

	got := DiscoverConfigPath(dir)
	if filepath.Base(got) != ".fmp.yaml" {
		t.Errorf("expected .fmp.yaml to be preferred over .fmp.yml, got %q", got)
	}
}

func TestDiscoverConfigPath_NoConfig(t *testing.T) {
	dir := t.TempDir()

	got := DiscoverConfigPath(dir)
	if got != "" {
		t.Errorf("expected empty string for no config, got %q", got)
	}
}

func TestLoadConfig_ParsesFullConfig(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, dir, ".fmp.yaml", `paths:
  - clusters/production
  - clusters/staging
recursive: true
helm: false
resolve-git: true
sops-decrypt: false
sort: true
exclude-crds: true
filters:
  - kind: FieldNormalizer
    match:
      kind: Secret
    fieldPaths:
      - path: [data, "tls.*"]
        action: replace
        placeholder: "<<auto-generated>>"
helm-settings:
  repository-cache: /tmp/helm-cache
`)

	cfg, err := LoadConfig(dir)
	if err != nil {
		t.Fatalf("LoadConfig() error = %v", err)
	}
	if cfg == nil {
		t.Fatal("expected config, got nil")
	}

	if len(cfg.Paths) != 2 {
		t.Errorf("expected 2 paths, got %d", len(cfg.Paths))
	}
	if !BoolOr(cfg.Recursive, false) {
		t.Error("expected recursive=true")
	}
	if BoolOr(cfg.Helm, true) {
		t.Error("expected helm=false")
	}
	if !BoolOr(cfg.ResolveGit, false) {
		t.Error("expected resolve-git=true")
	}
	if BoolOr(cfg.SOPSDecrypt, false) {
		t.Error("expected sops-decrypt=false")
	}
	if !BoolOr(cfg.Sort, false) {
		t.Error("expected sort=true")
	}
	if !BoolOr(cfg.ExcludeCRDs, false) {
		t.Error("expected exclude-crds=true")
	}
	if len(cfg.Filters.Filters) != 1 {
		t.Fatalf("expected 1 filter, got %d", len(cfg.Filters.Filters))
	}
	if cfg.HelmSettings == nil || cfg.HelmSettings.RepositoryCache != "/tmp/helm-cache" {
		t.Errorf("expected helm-settings.repository-cache=/tmp/helm-cache, got %v", cfg.HelmSettings)
	}
}

func TestLoadConfig_NoConfigReturnsNil(t *testing.T) {
	dir := t.TempDir()

	cfg, err := LoadConfig(dir)
	if err != nil {
		t.Fatalf("LoadConfig() error = %v", err)
	}
	if cfg != nil {
		t.Error("expected nil when no config file exists")
	}
}

func TestLoadConfig_EmptyConfig(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, dir, ".fmp.yaml", "{}\n")

	cfg, err := LoadConfig(dir)
	if err != nil {
		t.Fatalf("LoadConfig() error = %v", err)
	}
	if cfg == nil {
		t.Fatal("expected config, got nil")
	}
	if len(cfg.Paths) != 0 {
		t.Errorf("expected 0 paths, got %d", len(cfg.Paths))
	}
	if cfg.Recursive != nil {
		t.Errorf("expected nil Recursive, got %v", *cfg.Recursive)
	}
}

func TestLoadConfigFromPath_ExplicitPath(t *testing.T) {
	dir := t.TempDir()
	cfgPath := filepath.Join(dir, "my-custom-config.yaml")
	writeFile(t, dir, "my-custom-config.yaml", `sort: true
`)

	cfg, err := LoadConfigFromPath(cfgPath)
	if err != nil {
		t.Fatalf("LoadConfigFromPath() error = %v", err)
	}
	if !BoolOr(cfg.Sort, false) {
		t.Error("expected sort=true")
	}
}

func TestBoolOr(t *testing.T) {
	if BoolOr(nil, true) != true {
		t.Error("expected default true when nil")
	}
	if BoolOr(nil, false) != false {
		t.Error("expected default false when nil")
	}
	if BoolOr(BoolPtr(true), false) != true {
		t.Error("expected true from pointer, ignoring default")
	}
	if BoolOr(BoolPtr(false), true) != false {
		t.Error("expected false from pointer, ignoring default")
	}
}

func TestLoadConfig_GitHubLocation(t *testing.T) {
	dir := t.TempDir()
	mkdir(t, dir, ".github")
	writeFile(t, dir, ".github/fmp.yaml", `sort: true
exclude-crds: false
`)

	cfg, err := LoadConfig(dir)
	if err != nil {
		t.Fatalf("LoadConfig() error = %v", err)
	}
	if cfg == nil {
		t.Fatal("expected config from .github/fmp.yaml")
	}
	if !BoolOr(cfg.Sort, false) {
		t.Error("expected sort=true from .github/fmp.yaml")
	}
}

func TestLoadConfig_ParsesPolicies(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, dir, ".fmp.yaml", `policies:
  builtin:
    - image_update
    - namespace_delete
  modules:
    - .fmp/policies/*.rego
  inline:
    - |
      package fmp
      import rego.v1
      labels contains "custom-label" if true
  fail-on:
    - forbid_latest
  labels:
    image_update: image-update
    namespace_delete:
      - risky-change
      - cluster-admin-review
`)

	cfg, err := LoadConfig(dir)
	if err != nil {
		t.Fatalf("LoadConfig() error = %v", err)
	}
	if cfg == nil || cfg.Policies == nil {
		t.Fatal("expected policies config")
	}
	if len(cfg.Policies.Builtin) != 2 {
		t.Fatalf("expected 2 builtin policies, got %d", len(cfg.Policies.Builtin))
	}
	if got := cfg.Policies.Labels["image_update"]; len(got) != 1 || got[0] != "image-update" {
		t.Fatalf("expected scalar label mapping, got %v", got)
	}
	if got := cfg.Policies.Labels["namespace_delete"]; len(got) != 2 || got[0] != "risky-change" || got[1] != "cluster-admin-review" {
		t.Fatalf("expected list label mapping, got %v", got)
	}
	if cfg.SourcePath == "" {
		t.Fatal("expected SourcePath to be set")
	}
}

func TestLoadConfig_ParsesClusters(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, dir, ".fmp.yaml", `paths:
  - kube:clusters/kube
  - kube:clusters/shared
  - prod:clusters/prod
clusters:
  edge:
    - clusters/edge
`)

	cfg, err := LoadConfig(dir)
	if err != nil {
		t.Fatalf("LoadConfig() error = %v", err)
	}
	if cfg == nil {
		t.Fatal("expected config, got nil")
	}

	cp := cfg.ClusterPaths()
	if cp == nil {
		t.Fatal("expected ClusterPaths, got nil")
	}
	if len(cp["kube"]) != 2 {
		t.Errorf("expected 2 paths for kube, got %d", len(cp["kube"]))
	}
	if len(cp["prod"]) != 1 {
		t.Errorf("expected 1 path for prod, got %d", len(cp["prod"]))
	}
	if len(cp["edge"]) != 1 {
		t.Errorf("expected 1 path for edge, got %d", len(cp["edge"]))
	}
}

func TestLoadConfig_ClustersShorthand(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, dir, ".fmp.yaml", `clusters:
  kube: clusters/kube
`)

	cfg, err := LoadConfig(dir)
	if err != nil {
		t.Fatalf("LoadConfig() error = %v", err)
	}
	if cfg == nil {
		t.Fatal("expected config, got nil")
	}

	cp := cfg.ClusterPaths()
	if cp == nil {
		t.Fatal("expected ClusterPaths, got nil")
	}
	if len(cp["kube"]) != 1 || cp["kube"][0] != "clusters/kube" {
		t.Errorf("expected clusters/kube for kube, got %v", cp["kube"])
	}
}

func TestLoadConfig_FlatModeWhenNoPrefixes(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, dir, ".fmp.yaml", `paths:
  - clusters/kube
  - clusters/prod
`)

	cfg, err := LoadConfig(dir)
	if err != nil {
		t.Fatalf("LoadConfig() error = %v", err)
	}
	if cfg.ClusterPaths() != nil {
		t.Fatal("expected nil ClusterPaths for flat mode")
	}
}

func TestParseClusterPath(t *testing.T) {
	tests := []struct {
		input       string
		wantCluster string
		wantPath    string
	}{
		{"kube:clusters/kube", "kube", "clusters/kube"},
		{"clusters/kube", "", "clusters/kube"},
		{":clusters/kube", "", ":clusters/kube"},
		{"kube:", "kube", ""},
	}
	for _, tt := range tests {
		gotCluster, gotPath := ParseClusterPath(tt.input)
		if gotCluster != tt.wantCluster || gotPath != tt.wantPath {
			t.Errorf("ParseClusterPath(%q) = (%q, %q), want (%q, %q)",
				tt.input, gotCluster, gotPath, tt.wantCluster, tt.wantPath)
		}
	}
}

func writeFile(t *testing.T, dir, name, content string) {
	t.Helper()
	full := filepath.Join(dir, name)
	if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
		t.Fatalf("creating dir: %v", err)
	}
	if err := os.WriteFile(full, []byte(content), 0o644); err != nil {
		t.Fatalf("writing %s: %v", name, err)
	}
}

func mkdir(t *testing.T, dir, name string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Join(dir, name), 0o755); err != nil {
		t.Fatalf("creating dir %s: %v", name, err)
	}
}
