apiVersion: platform.example.org/v1alpha1
kind: XPlatform
metadata:
  name: checkout
  namespace: apps
spec:
  config:
    environment: production
    image: nginx:1.27.4
    replicas: 2
    size: small
    dbInstanceClass: db.t3.small
    storage: 20
    cacheGiB: 1
    expose: false
    host: checkout.example.test
    logs: false
    debug: true
