package diff

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"sort"
	"strings"

	"github.com/tobiash/gitops-preview-toolkit/pkg/filter"
	"github.com/tobiash/gitops-preview-toolkit/pkg/render"
	"gopkg.in/yaml.v3"
	"sigs.k8s.io/kustomize/api/resource"
	"sigs.k8s.io/kustomize/kyaml/resid"
)

type FieldDiff struct {
	LogicalID string
	GVK       resid.Gvk
	Name      string
	Namespace string
	FieldPath []string
	IsLeaf    bool
}

type NormalizationRule struct {
	Match      filter.MatchCriteria
	FieldPaths []filter.FieldPath
}

func DetectPermadiffs(a, b *render.Render) ([]FieldDiff, error) {
	var diffs []FieldDiff

	resourcesA := buildResourceMap(a)

	for _, rb := range b.Resources() {
		id := rb.CurId()
		ra, ok := resourcesA[id.String()]
		if !ok {
			continue
		}

		mapA, errA := ra.Map()
		mapB, errB := rb.Map()
		if errA != nil || errB != nil {
			continue
		}

		fieldDiffs := findDifferences(mapA, mapB, nil)
		for _, fd := range fieldDiffs {
			diffs = append(diffs, FieldDiff{
				GVK:       ra.GetGvk(),
				Name:      ra.GetName(),
				Namespace: ra.GetNamespace(),
				FieldPath: fd.path,
				IsLeaf:    fd.isLeaf,
			})
		}
	}

	return diffs, nil
}

func GenerateFilterConfig(diffs []FieldDiff) ([]byte, error) {
	rules := GroupDiffsToRules(diffs)
	if len(rules) == 0 {
		return []byte("# No permadiffs detected.\n"), nil
	}

	var filters []map[string]any
	for _, rule := range rules {
		fn := filter.FieldNormalizer{
			Match:      rule.Match,
			FieldPaths: rule.FieldPaths,
		}
		m := map[string]any{
			"kind":       "FieldNormalizer",
			"match":      fn.Match,
			"fieldPaths": fn.FieldPaths,
		}
		filters = append(filters, m)
	}

	cfg := map[string]any{
		"filters": filters,
	}

	var buf strings.Builder
	buf.WriteString("# Auto-generated by fmp detect-permadiffs\n")
	enc := yaml.NewEncoder(&buf)
	if err := enc.Encode(cfg); err != nil {
		return nil, fmt.Errorf("encoding filter config: %w", err)
	}
	if err := enc.Close(); err != nil {
		return nil, fmt.Errorf("closing encoder: %w", err)
	}
	return []byte(buf.String()), nil
}

func WritePermadiffConfig(a, b *render.Render, out io.Writer) error {
	diffs, err := DetectPermadiffs(a, b)
	if err != nil {
		return err
	}

	config, err := GenerateFilterConfig(diffs)
	if err != nil {
		return err
	}

	_, err = out.Write(config)
	return err
}

type fieldDiffEntry struct {
	path   []string
	isLeaf bool
}

func findDifferences(a, b map[string]any, prefix []string) []fieldDiffEntry {
	var diffs []fieldDiffEntry

	allKeys := make(map[string]bool)
	for k := range a {
		allKeys[k] = true
	}
	for k := range b {
		allKeys[k] = true
	}

	for key := range allKeys {
		va, okA := a[key]
		vb, okB := b[key]
		path := make([]string, len(prefix)+1)
		copy(path, prefix)
		path[len(prefix)] = key

		if !okA || !okB {
			diffs = append(diffs, fieldDiffEntry{path: path, isLeaf: true})
			continue
		}

		av, aOk := va.(map[string]any)
		bv, bOk := vb.(map[string]any)
		if aOk && bOk {
			subDiffs := findDifferences(av, bv, path)
			if len(subDiffs) == 0 {
				continue
			}
			diffs = append(diffs, subDiffs...)
			continue
		}

		aArr, aArrOk := va.([]any)
		bArr, bArrOk := vb.([]any)
		if aArrOk && bArrOk {
			subDiffs := findArrayDifferences(aArr, bArr, path)
			diffs = append(diffs, subDiffs...)
			continue
		}

		if !equalFieldValues(va, vb) {
			diffs = append(diffs, fieldDiffEntry{path: path, isLeaf: true})
		}
	}

	return diffs
}

func findArrayDifferences(a, b []any, prefix []string) []fieldDiffEntry {
	var diffs []fieldDiffEntry
	maxLen := len(a)
	if len(b) > maxLen {
		maxLen = len(b)
	}

	for i := 0; i < maxLen; i++ {
		idxPath := make([]string, len(prefix)+1)
		copy(idxPath, prefix)
		idxPath[len(prefix)] = fmt.Sprintf("[%d]", i)

		if i >= len(a) || i >= len(b) {
			diffs = append(diffs, fieldDiffEntry{path: idxPath, isLeaf: true})
			continue
		}

		aMap, aOk := a[i].(map[string]any)
		bMap, bOk := b[i].(map[string]any)
		if aOk && bOk {
			subDiffs := findDifferences(aMap, bMap, idxPath)
			diffs = append(diffs, subDiffs...)
			continue
		}

		aArr, aArrOk := a[i].([]any)
		bArr, bArrOk := b[i].([]any)
		if aArrOk && bArrOk {
			subDiffs := findArrayDifferences(aArr, bArr, idxPath)
			diffs = append(diffs, subDiffs...)
			continue
		}

		if !equalFieldValues(a[i], b[i]) {
			diffs = append(diffs, fieldDiffEntry{path: idxPath, isLeaf: true})
		}
	}

	return diffs
}

// Use the same canonical scalar semantics as inventory comparison. Display
// strings collapse distinct YAML values such as !!str 1 and !!int 1.
func equalFieldValues(a, b any) bool {
	left, leftErr := json.Marshal(a)
	right, rightErr := json.Marshal(b)
	return leftErr == nil && rightErr == nil && bytes.Equal(left, right)
}

func isArrayIndex(s string) bool {
	return len(s) > 2 && s[0] == '[' && s[len(s)-1] == ']'
}

func normalizePathElements(path []string) []string {
	normalized := make([]string, len(path))
	for i, p := range path {
		if isArrayIndex(p) {
			normalized[i] = "[*]"
		} else {
			normalized[i] = p
		}
	}
	return normalized
}

func GroupDiffsToRules(diffs []FieldDiff) []NormalizationRule {
	type gvkKey struct {
		group, version, kind string
	}

	fieldCounts := make(map[string]int)

	for _, d := range diffs {
		gk := gvkKey{d.GVK.Group, d.GVK.Version, d.GVK.Kind}
		normalized := normalizePathElements(d.FieldPath)
		fieldCounts[gk.group+"/"+gk.kind+"/"+strings.Join(normalized, "/")]++
	}

	gvkFields := make(map[gvkKey][]fieldInfo)

	for _, d := range diffs {
		gk := gvkKey{d.GVK.Group, d.GVK.Version, d.GVK.Kind}
		normalized := normalizePathElements(d.FieldPath)
		normStr := strings.Join(normalized, "/")
		key := gk.group + "/" + gk.kind + "/" + normStr
		count := fieldCounts[key]

		exists := false
		for _, f := range gvkFields[gk] {
			if strings.Join(f.path, "/") == normStr {
				exists = true
				break
			}
		}
		if !exists {
			gvkFields[gk] = append(gvkFields[gk], fieldInfo{
				path:   normalized,
				isLeaf: d.IsLeaf,
				count:  count,
			})
		}
	}

	var rules []NormalizationRule

	for gk, fields := range gvkFields {
		match := filter.MatchCriteria{
			Group:   gk.group,
			Version: gk.version,
			Kind:    gk.kind,
		}

		groupedPaths := inferGlobPatterns(fields)

		var fieldPaths []filter.FieldPath
		for _, gp := range groupedPaths {
			action := filter.ActionReplace
			if !gp.isLeaf {
				action = filter.ActionRemove
			}
			fieldPaths = append(fieldPaths, filter.FieldPath{
				Path:        gp.path,
				Action:      action,
				Placeholder: "<<auto-generated>>",
			})
		}

		if len(fieldPaths) > 0 {
			rules = append(rules, NormalizationRule{
				Match:      match,
				FieldPaths: fieldPaths,
			})
		}
	}

	sort.Slice(rules, func(i, j int) bool {
		if rules[i].Match.Kind != rules[j].Match.Kind {
			return rules[i].Match.Kind < rules[j].Match.Kind
		}
		return rules[i].Match.Group < rules[j].Match.Group
	})

	return rules
}

type fieldInfo struct {
	path   []string
	isLeaf bool
	count  int
}

type groupedPath struct {
	path   []string
	isLeaf bool
}

func inferGlobPatterns(fields []fieldInfo) []groupedPath {
	type prefixGroup struct {
		prefix   []string
		suffixes []string
		isLeaf   bool
	}

	prefixMap := make(map[string]*prefixGroup)

	for _, f := range fields {
		if len(f.path) < 2 {
			key := strings.Join(f.path, "/")
			if _, ok := prefixMap[key]; !ok {
				prefixMap[key] = &prefixGroup{
					prefix: f.path,
					isLeaf: f.isLeaf,
				}
			}
			continue
		}

		prefix := f.path[:len(f.path)-1]
		suffix := f.path[len(f.path)-1]
		key := strings.Join(prefix, "/")

		if pg, ok := prefixMap[key]; ok {
			found := false
			for _, s := range pg.suffixes {
				if s == suffix {
					found = true
					break
				}
			}
			if !found {
				pg.suffixes = append(pg.suffixes, suffix)
			}
		} else {
			prefixMap[key] = &prefixGroup{
				prefix:   prefix,
				suffixes: []string{suffix},
				isLeaf:   f.isLeaf,
			}
		}
	}

	var result []groupedPath
	for _, pg := range prefixMap {
		isDataField := len(pg.prefix) == 1 && (pg.prefix[0] == "data" || pg.prefix[0] == "stringData")

		if !isDataField && len(pg.suffixes) >= 2 {
			result = append(result, groupedPath{
				path:   append(pg.prefix, "*"),
				isLeaf: pg.isLeaf,
			})
		} else {
			for _, s := range pg.suffixes {
				newPath := make([]string, len(pg.prefix)+1)
				copy(newPath, pg.prefix)
				newPath[len(pg.prefix)] = s
				result = append(result, groupedPath{
					path:   newPath,
					isLeaf: pg.isLeaf,
				})
			}
			if len(pg.suffixes) == 0 {
				result = append(result, groupedPath{
					path:   pg.prefix,
					isLeaf: pg.isLeaf,
				})
			}
		}
	}

	sort.Slice(result, func(i, j int) bool {
		return strings.Join(result[i].path, "/") < strings.Join(result[j].path, "/")
	})

	return result
}

func buildResourceMap(r *render.Render) map[string]*resource.Resource {
	m := make(map[string]*resource.Resource)
	for _, res := range r.Resources() {
		m[res.CurId().String()] = res
	}
	return m
}
